name: test rickstaa/action-contains-tag
on:
  push:
    branches:
      - main
jobs:
  check-if-tag-exists:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: rickstaa/action-contains-tag@main-test-git-security-fix
        id: contains_tag
        with:
          reference: "main"
          tag: "Latest"
      - run: |
          if [[ ${{ steps.contains_tag.outputs.retval }} != 'true' ]]; then
            echo "Branch/commit did contain the tag :)."
          else
            echo "Branch/commit did not contain the tag."
          fi
